// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250102000000_AddBindToken")]
public partial class AddBindToken : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<string>(
            name: "BindToken",
            table: "AdventCampaigns",
            type: "TEXT",
            maxLength: 64,
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "IX_AdventCampaigns_BindToken",
            table: "AdventCampaigns",
            column: "BindToken");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "IX_AdventCampaigns_BindToken",
            table: "AdventCampaigns");

        migrationBuilder.DropColumn(
            name: "BindToken",
            table: "AdventCampaigns");
    }
}
