// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250101000000_Init")]
public partial class Init : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Users",
            columns: table => new
            {
                Id = table.Column<long>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                TelegramId = table.Column<long>(type: "INTEGER", nullable: false),
                Username = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                FirstName = table.Column<string>(type: "TEXT", maxLength: 128, nullable: true),
                CreatedAtUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                LastSeenAtUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Users", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "AdventCampaigns",
            columns: table => new
            {
                Id = table.Column<long>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                OwnerUserId = table.Column<long>(type: "INTEGER", nullable: false),
                StartDate = table.Column<DateTime>(type: "TEXT", nullable: false),
                EndDate = table.Column<DateTime>(type: "TEXT", nullable: false),
                DefaultSendTime = table.Column<TimeSpan>(type: "TEXT", nullable: false),
                Status = table.Column<int>(type: "INTEGER", nullable: false),
                RecipientUserId = table.Column<long>(type: "INTEGER", nullable: true),
                RecipientStatus = table.Column<int>(type: "INTEGER", nullable: false),
                Name = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                CreatedAtUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                UpdatedAtUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_AdventCampaigns", x => x.Id);
                table.ForeignKey(
                    name: "FK_AdventCampaigns_Users_OwnerUserId",
                    column: x => x.OwnerUserId,
                    principalTable: "Users",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "FK_AdventCampaigns_Users_RecipientUserId",
                    column: x => x.RecipientUserId,
                    principalTable: "Users",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "DeliveryLogs",
            columns: table => new
            {
                Id = table.Column<long>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                CampaignId = table.Column<long>(type: "INTEGER", nullable: false),
                RecipientUserId = table.Column<long>(type: "INTEGER", nullable: false),
                Date = table.Column<DateTime>(type: "TEXT", nullable: false),
                Status = table.Column<int>(type: "INTEGER", nullable: false),
                Attempts = table.Column<int>(type: "INTEGER", nullable: false),
                Error = table.Column<string>(type: "TEXT", nullable: true),
                TelegramMessageId = table.Column<int>(type: "INTEGER", nullable: true),
                SentAtUtc = table.Column<DateTime>(type: "TEXT", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_DeliveryLogs", x => x.Id);
                table.ForeignKey(
                    name: "FK_DeliveryLogs_AdventCampaigns_CampaignId",
                    column: x => x.CampaignId,
                    principalTable: "AdventCampaigns",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "FK_DeliveryLogs_Users_RecipientUserId",
                    column: x => x.RecipientUserId,
                    principalTable: "Users",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "AdventDays",
            columns: table => new
            {
                Id = table.Column<long>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                CampaignId = table.Column<long>(type: "INTEGER", nullable: false),
                Date = table.Column<DateTime>(type: "TEXT", nullable: false),
                Text = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: false),
                OverrideSendTime = table.Column<TimeSpan>(type: "TEXT", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_AdventDays", x => x.Id);
                table.ForeignKey(
                    name: "FK_AdventDays_AdventCampaigns_CampaignId",
                    column: x => x.CampaignId,
                    principalTable: "AdventCampaigns",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_AdventCampaigns_OwnerUserId",
            table: "AdventCampaigns",
            column: "OwnerUserId");

        migrationBuilder.CreateIndex(
            name: "IX_AdventCampaigns_RecipientUserId",
            table: "AdventCampaigns",
            column: "RecipientUserId");

        migrationBuilder.CreateIndex(
            name: "IX_Campaign_Owner_Period",
            table: "AdventCampaigns",
            columns: new[] { "OwnerUserId", "StartDate", "EndDate" });

        migrationBuilder.CreateIndex(
            name: "IX_AdventDays_CampaignId",
            table: "AdventDays",
            column: "CampaignId");

        migrationBuilder.CreateIndex(
            name: "IX_AdventDays_CampaignId_Date",
            table: "AdventDays",
            columns: new[] { "CampaignId", "Date" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_DeliveryLogs_CampaignId",
            table: "DeliveryLogs",
            column: "CampaignId");

        migrationBuilder.CreateIndex(
            name: "IX_DeliveryLogs_CampaignId_Date_RecipientUserId",
            table: "DeliveryLogs",
            columns: new[] { "CampaignId", "Date", "RecipientUserId" },
            unique: true,
            filter: "Status = 0");

        migrationBuilder.CreateIndex(
            name: "IX_Delivery_Idem",
            table: "DeliveryLogs",
            columns: new[] { "CampaignId", "Date", "RecipientUserId", "Status" });

        migrationBuilder.CreateIndex(
            name: "IX_DeliveryLogs_RecipientUserId",
            table: "DeliveryLogs",
            column: "RecipientUserId");

        migrationBuilder.CreateIndex(
            name: "IX_Users_TelegramId",
            table: "Users",
            column: "TelegramId",
            unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "AdventDays");

        migrationBuilder.DropTable(
            name: "DeliveryLogs");

        migrationBuilder.DropTable(
            name: "AdventCampaigns");

        migrationBuilder.DropTable(
            name: "Users");
    }
}
