// <auto-generated />
using System;
using Domain.Advent;
using Domain.Delivery;
using Domain.Users;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6");

        var dateOnlyConverter = new ValueConverter<DateOnly, DateTime>(
            d => d.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc),
            d => DateOnly.FromDateTime(DateTime.SpecifyKind(d, DateTimeKind.Utc)));

        var timeOnlyConverter = new ValueConverter<TimeOnly, TimeSpan>(
            t => t.ToTimeSpan(),
            t => TimeOnly.FromTimeSpan(t));

        var nullableTimeOnlyConverter = new ValueConverter<TimeOnly?, TimeSpan?>(
            t => t.HasValue ? t.Value.ToTimeSpan() : null,
            t => t.HasValue ? TimeOnly.FromTimeSpan(t.Value) : null);

        modelBuilder.Entity<User>(b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<string>("FirstName")
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<DateTime>("LastSeenAtUtc")
                .HasColumnType("TEXT");

            b.Property<long>("TelegramId")
                .HasColumnType("INTEGER");

            b.Property<string>("Username")
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("TelegramId")
                .IsUnique();

            b.ToTable("Users");
        });

        modelBuilder.Entity<AdventCampaign>(b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<string>("BindToken")
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<TimeSpan>("DefaultSendTime")
                .HasColumnType("TEXT")
                .HasConversion(timeOnlyConverter);

            b.Property<DateTime>("EndDate")
                .HasColumnType("TEXT")
                .HasConversion(dateOnlyConverter);

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<long>("OwnerUserId")
                .HasColumnType("INTEGER");

            b.Property<long?>("RecipientUserId")
                .HasColumnType("INTEGER");

            b.Property<int>("RecipientStatus")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("StartDate")
                .HasColumnType("TEXT")
                .HasConversion(dateOnlyConverter);

            b.Property<int>("Status")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("BindToken");

            b.HasIndex("OwnerUserId");

            b.HasIndex("RecipientUserId");

            b.HasIndex("OwnerUserId", "StartDate", "EndDate")
                .HasDatabaseName("IX_Campaign_Owner_Period");

            b.ToTable("AdventCampaigns");
        });

        modelBuilder.Entity<AdventDay>(b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<long>("CampaignId")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("Date")
                .HasColumnType("TEXT")
                .HasConversion(dateOnlyConverter);

            b.Property<TimeSpan?>("OverrideSendTime")
                .HasColumnType("TEXT")
                .HasConversion(nullableTimeOnlyConverter);

            b.Property<string>("Text")
                .IsRequired()
                .HasMaxLength(4096)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("CampaignId");

            b.HasIndex("CampaignId", "Date")
                .IsUnique();

            b.ToTable("AdventDays");
        });

        modelBuilder.Entity<DeliveryLog>(b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("Attempts")
                .HasColumnType("INTEGER");

            b.Property<long>("CampaignId")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("Date")
                .HasColumnType("TEXT")
                .HasConversion(dateOnlyConverter);

            b.Property<string>("Error")
                .HasColumnType("TEXT");

            b.Property<long>("RecipientUserId")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<DateTime>("LastAttemptAtUtc")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("SentAtUtc")
                .HasColumnType("TEXT");

            b.Property<int>("Status")
                .HasColumnType("INTEGER");

            b.Property<int?>("TelegramMessageId")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("CampaignId");

            b.HasIndex("RecipientUserId");

            b.HasIndex("CampaignId", "Date", "RecipientUserId", "Status")
                .HasDatabaseName("IX_Delivery_Idem");

            b.HasIndex("CampaignId", "Date", "RecipientUserId")
                .IsUnique()
                .HasFilter("Status = 0");

            b.ToTable("DeliveryLogs");
        });

        modelBuilder.Entity<AdventDay>()
            .HasOne<AdventCampaign>()
            .WithMany(c => c.Days)
            .HasForeignKey("CampaignId")
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<AdventCampaign>()
            .HasOne<User>()
            .WithMany()
            .HasForeignKey("OwnerUserId")
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<AdventCampaign>()
            .HasOne<User>()
            .WithMany()
            .HasForeignKey("RecipientUserId")
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<DeliveryLog>()
            .HasOne<AdventCampaign>()
            .WithMany()
            .HasForeignKey("CampaignId")
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<DeliveryLog>()
            .HasOne<User>()
            .WithMany()
            .HasForeignKey("RecipientUserId")
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<AdventCampaign>()
            .Navigation(c => c.Days);
#pragma warning restore 612, 618
    }
}
