<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>
